[package]
name = "wwise_analysis"
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true
readme = false

[dependencies]
wwise_format = { path = "../format" }
