on: [push]

name: Build

jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features --verbose
      - uses: actions/upload-artifact@v4
        with:
          name: binaries-${{ matrix.runs-on }}
          path: target/release/*.exe
